name: room_finder_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  # Base
  nb_utils: ^4.6.16
  google_fonts: ^4.0.3
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.2

  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  firebase_auth: ^4.2.5
  flutter_datetime_picker: ^1.5.1
  flutter_masked_text: ^0.8.0
  pattern_formatter: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  simple_animations: 4.0.2
  animations: ^2.0.7
  flutter_keyboard_visibility: ^5.4.0
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  plugin_platform_interface: ^2.0.0
  image_picker: ^0.8.6+2
  image_picker_platform_interface: ^2.6.2
  firebase_messaging: ^14.2.5
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  plugin_platform_interface: ^2.0.0
  image_picker: ^0.8.6+2
  image_picker_platform_interface: ^2.6.2
  video_player: ^2.5.1
  firebase_messaging: ^14.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.4
  intl: ^0.17.0
  http: ^0.13.5

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/roomFinding/
    - images/le-chan/
    - images/san-pham/
    - images/stockMarket/
    - images/stockMarket/icons/
    - images/stockMarket/stock/
    - images/banking/
    - images/walletApp/
